/*
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractQuickGUIScopeProvider extends DelegatingScopeProvider {
}
