/*
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractQuickGUIValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.example.quickgui2.quickGUI.QuickGUIPackage.eINSTANCE);
		return result;
	}
}
