/*
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.example.quickgui2.quickGUI.Button;
import org.example.quickgui2.quickGUI.Field;
import org.example.quickgui2.quickGUI.Panel;
import org.example.quickgui2.quickGUI.Program;
import org.example.quickgui2.quickGUI.QuickGUIPackage;
import org.example.quickgui2.quickGUI.Window;
import org.example.quickgui2.services.QuickGUIGrammarAccess;

@SuppressWarnings("all")
public class QuickGUISemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private QuickGUIGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == QuickGUIPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case QuickGUIPackage.BUTTON:
				sequence_Button(context, (Button) semanticObject); 
				return; 
			case QuickGUIPackage.FIELD:
				sequence_Field(context, (Field) semanticObject); 
				return; 
			case QuickGUIPackage.PANEL:
				sequence_Panel(context, (Panel) semanticObject); 
				return; 
			case QuickGUIPackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case QuickGUIPackage.WINDOW:
				sequence_Window(context, (Window) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Component returns Button
	 *     Button returns Button
	 *
	 * Constraint:
	 *     (text=STRING action=ButtonAction)
	 * </pre>
	 */
	protected void sequence_Button(ISerializationContext context, Button semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, QuickGUIPackage.Literals.BUTTON__TEXT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuickGUIPackage.Literals.BUTTON__TEXT));
			if (transientValues.isValueTransient(semanticObject, QuickGUIPackage.Literals.BUTTON__ACTION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuickGUIPackage.Literals.BUTTON__ACTION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getButtonAccess().getTextSTRINGTerminalRuleCall_1_0(), semanticObject.getText());
		feeder.accept(grammarAccess.getButtonAccess().getActionButtonActionEnumRuleCall_3_0(), semanticObject.getAction());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Component returns Field
	 *     Field returns Field
	 *
	 * Constraint:
	 *     (label=STRING name=ID type=FieldType)
	 * </pre>
	 */
	protected void sequence_Field(ISerializationContext context, Field semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, QuickGUIPackage.Literals.FIELD__LABEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuickGUIPackage.Literals.FIELD__LABEL));
			if (transientValues.isValueTransient(semanticObject, QuickGUIPackage.Literals.FIELD__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuickGUIPackage.Literals.FIELD__NAME));
			if (transientValues.isValueTransient(semanticObject, QuickGUIPackage.Literals.FIELD__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuickGUIPackage.Literals.FIELD__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFieldAccess().getLabelSTRINGTerminalRuleCall_1_0(), semanticObject.getLabel());
		feeder.accept(grammarAccess.getFieldAccess().getNameIDTerminalRuleCall_3_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getFieldAccess().getTypeFieldTypeEnumRuleCall_5_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Panel returns Panel
	 *
	 * Constraint:
	 *     (title=STRING components+=Component*)
	 * </pre>
	 */
	protected void sequence_Panel(ISerializationContext context, Panel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     window=Window
	 * </pre>
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, QuickGUIPackage.Literals.PROGRAM__WINDOW) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuickGUIPackage.Literals.PROGRAM__WINDOW));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getProgramAccess().getWindowWindowParserRuleCall_2_0(), semanticObject.getWindow());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Window returns Window
	 *
	 * Constraint:
	 *     (title=STRING panel=Panel)
	 * </pre>
	 */
	protected void sequence_Window(ISerializationContext context, Window semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, QuickGUIPackage.Literals.WINDOW__TITLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuickGUIPackage.Literals.WINDOW__TITLE));
			if (transientValues.isValueTransient(semanticObject, QuickGUIPackage.Literals.WINDOW__PANEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, QuickGUIPackage.Literals.WINDOW__PANEL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWindowAccess().getTitleSTRINGTerminalRuleCall_1_0(), semanticObject.getTitle());
		feeder.accept(grammarAccess.getWindowAccess().getPanelPanelParserRuleCall_3_0(), semanticObject.getPanel());
		feeder.finish();
	}
	
	
}
