/**
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.quickGUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Button</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quickgui2.quickGUI.Button#getText <em>Text</em>}</li>
 *   <li>{@link org.example.quickgui2.quickGUI.Button#getAction <em>Action</em>}</li>
 * </ul>
 *
 * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getButton()
 * @model
 * @generated
 */
public interface Button extends Component
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getButton_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link org.example.quickgui2.quickGUI.Button#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * The literals are from the enumeration {@link org.example.quickgui2.quickGUI.ButtonAction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see org.example.quickgui2.quickGUI.ButtonAction
   * @see #setAction(ButtonAction)
   * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getButton_Action()
   * @model
   * @generated
   */
  ButtonAction getAction();

  /**
   * Sets the value of the '{@link org.example.quickgui2.quickGUI.Button#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see org.example.quickgui2.quickGUI.ButtonAction
   * @see #getAction()
   * @generated
   */
  void setAction(ButtonAction value);

} // Button
