/**
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.quickGUI;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getComponent()
 * @model
 * @generated
 */
public interface Component extends EObject
{
} // Component
