/**
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.quickGUI;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quickgui2.quickGUI.Field#getLabel <em>Label</em>}</li>
 *   <li>{@link org.example.quickgui2.quickGUI.Field#getName <em>Name</em>}</li>
 *   <li>{@link org.example.quickgui2.quickGUI.Field#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getField()
 * @model
 * @generated
 */
public interface Field extends Component
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getField_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link org.example.quickgui2.quickGUI.Field#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getField_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.example.quickgui2.quickGUI.Field#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.example.quickgui2.quickGUI.FieldType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.example.quickgui2.quickGUI.FieldType
   * @see #setType(FieldType)
   * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getField_Type()
   * @model
   * @generated
   */
  FieldType getType();

  /**
   * Sets the value of the '{@link org.example.quickgui2.quickGUI.Field#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.example.quickgui2.quickGUI.FieldType
   * @see #getType()
   * @generated
   */
  void setType(FieldType value);

} // Field
