/**
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.quickGUI;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Panel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quickgui2.quickGUI.Panel#getTitle <em>Title</em>}</li>
 *   <li>{@link org.example.quickgui2.quickGUI.Panel#getComponents <em>Components</em>}</li>
 * </ul>
 *
 * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getPanel()
 * @model
 * @generated
 */
public interface Panel extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getPanel_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.example.quickgui2.quickGUI.Panel#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Components</b></em>' containment reference list.
   * The list contents are of type {@link org.example.quickgui2.quickGUI.Component}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' containment reference list.
   * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getPanel_Components()
   * @model containment="true"
   * @generated
   */
  EList<Component> getComponents();

} // Panel
