/**
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.quickGUI;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quickgui2.quickGUI.Program#getWindow <em>Window</em>}</li>
 * </ul>
 *
 * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Window</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Window</em>' containment reference.
   * @see #setWindow(Window)
   * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getProgram_Window()
   * @model containment="true"
   * @generated
   */
  Window getWindow();

  /**
   * Sets the value of the '{@link org.example.quickgui2.quickGUI.Program#getWindow <em>Window</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Window</em>' containment reference.
   * @see #getWindow()
   * @generated
   */
  void setWindow(Window value);

} // Program
