/**
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.quickGUI;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.example.quickgui2.quickGUI.QuickGUIFactory
 * @model kind="package"
 * @generated
 */
public interface QuickGUIPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "quickGUI";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.example.org/quickgui2/QuickGUI";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "quickGUI";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  QuickGUIPackage eINSTANCE = org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl.init();

  /**
   * The meta object id for the '{@link org.example.quickgui2.quickGUI.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.quickgui2.quickGUI.impl.ProgramImpl
   * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Window</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__WINDOW = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.example.quickgui2.quickGUI.impl.WindowImpl <em>Window</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.quickgui2.quickGUI.impl.WindowImpl
   * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getWindow()
   * @generated
   */
  int WINDOW = 1;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW__TITLE = 0;

  /**
   * The feature id for the '<em><b>Panel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW__PANEL = 1;

  /**
   * The number of structural features of the '<em>Window</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WINDOW_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.example.quickgui2.quickGUI.impl.PanelImpl <em>Panel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.quickgui2.quickGUI.impl.PanelImpl
   * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getPanel()
   * @generated
   */
  int PANEL = 2;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL__TITLE = 0;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL__COMPONENTS = 1;

  /**
   * The number of structural features of the '<em>Panel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PANEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.example.quickgui2.quickGUI.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.quickgui2.quickGUI.impl.ComponentImpl
   * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 3;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.example.quickgui2.quickGUI.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.quickgui2.quickGUI.impl.FieldImpl
   * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getField()
   * @generated
   */
  int FIELD = 4;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__LABEL = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__NAME = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__TYPE = COMPONENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.example.quickgui2.quickGUI.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.quickgui2.quickGUI.impl.ButtonImpl
   * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 5;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__TEXT = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__ACTION = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.example.quickgui2.quickGUI.FieldType <em>Field Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.quickgui2.quickGUI.FieldType
   * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getFieldType()
   * @generated
   */
  int FIELD_TYPE = 6;

  /**
   * The meta object id for the '{@link org.example.quickgui2.quickGUI.ButtonAction <em>Button Action</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.example.quickgui2.quickGUI.ButtonAction
   * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getButtonAction()
   * @generated
   */
  int BUTTON_ACTION = 7;


  /**
   * Returns the meta object for class '{@link org.example.quickgui2.quickGUI.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.example.quickgui2.quickGUI.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link org.example.quickgui2.quickGUI.Program#getWindow <em>Window</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Window</em>'.
   * @see org.example.quickgui2.quickGUI.Program#getWindow()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Window();

  /**
   * Returns the meta object for class '{@link org.example.quickgui2.quickGUI.Window <em>Window</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Window</em>'.
   * @see org.example.quickgui2.quickGUI.Window
   * @generated
   */
  EClass getWindow();

  /**
   * Returns the meta object for the attribute '{@link org.example.quickgui2.quickGUI.Window#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.example.quickgui2.quickGUI.Window#getTitle()
   * @see #getWindow()
   * @generated
   */
  EAttribute getWindow_Title();

  /**
   * Returns the meta object for the containment reference '{@link org.example.quickgui2.quickGUI.Window#getPanel <em>Panel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Panel</em>'.
   * @see org.example.quickgui2.quickGUI.Window#getPanel()
   * @see #getWindow()
   * @generated
   */
  EReference getWindow_Panel();

  /**
   * Returns the meta object for class '{@link org.example.quickgui2.quickGUI.Panel <em>Panel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Panel</em>'.
   * @see org.example.quickgui2.quickGUI.Panel
   * @generated
   */
  EClass getPanel();

  /**
   * Returns the meta object for the attribute '{@link org.example.quickgui2.quickGUI.Panel#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.example.quickgui2.quickGUI.Panel#getTitle()
   * @see #getPanel()
   * @generated
   */
  EAttribute getPanel_Title();

  /**
   * Returns the meta object for the containment reference list '{@link org.example.quickgui2.quickGUI.Panel#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.example.quickgui2.quickGUI.Panel#getComponents()
   * @see #getPanel()
   * @generated
   */
  EReference getPanel_Components();

  /**
   * Returns the meta object for class '{@link org.example.quickgui2.quickGUI.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see org.example.quickgui2.quickGUI.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for class '{@link org.example.quickgui2.quickGUI.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see org.example.quickgui2.quickGUI.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the attribute '{@link org.example.quickgui2.quickGUI.Field#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see org.example.quickgui2.quickGUI.Field#getLabel()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Label();

  /**
   * Returns the meta object for the attribute '{@link org.example.quickgui2.quickGUI.Field#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.example.quickgui2.quickGUI.Field#getName()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Name();

  /**
   * Returns the meta object for the attribute '{@link org.example.quickgui2.quickGUI.Field#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.example.quickgui2.quickGUI.Field#getType()
   * @see #getField()
   * @generated
   */
  EAttribute getField_Type();

  /**
   * Returns the meta object for class '{@link org.example.quickgui2.quickGUI.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see org.example.quickgui2.quickGUI.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for the attribute '{@link org.example.quickgui2.quickGUI.Button#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.example.quickgui2.quickGUI.Button#getText()
   * @see #getButton()
   * @generated
   */
  EAttribute getButton_Text();

  /**
   * Returns the meta object for the attribute '{@link org.example.quickgui2.quickGUI.Button#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see org.example.quickgui2.quickGUI.Button#getAction()
   * @see #getButton()
   * @generated
   */
  EAttribute getButton_Action();

  /**
   * Returns the meta object for enum '{@link org.example.quickgui2.quickGUI.FieldType <em>Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Field Type</em>'.
   * @see org.example.quickgui2.quickGUI.FieldType
   * @generated
   */
  EEnum getFieldType();

  /**
   * Returns the meta object for enum '{@link org.example.quickgui2.quickGUI.ButtonAction <em>Button Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Button Action</em>'.
   * @see org.example.quickgui2.quickGUI.ButtonAction
   * @generated
   */
  EEnum getButtonAction();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  QuickGUIFactory getQuickGUIFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.example.quickgui2.quickGUI.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.quickgui2.quickGUI.impl.ProgramImpl
     * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Window</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__WINDOW = eINSTANCE.getProgram_Window();

    /**
     * The meta object literal for the '{@link org.example.quickgui2.quickGUI.impl.WindowImpl <em>Window</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.quickgui2.quickGUI.impl.WindowImpl
     * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getWindow()
     * @generated
     */
    EClass WINDOW = eINSTANCE.getWindow();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WINDOW__TITLE = eINSTANCE.getWindow_Title();

    /**
     * The meta object literal for the '<em><b>Panel</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WINDOW__PANEL = eINSTANCE.getWindow_Panel();

    /**
     * The meta object literal for the '{@link org.example.quickgui2.quickGUI.impl.PanelImpl <em>Panel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.quickgui2.quickGUI.impl.PanelImpl
     * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getPanel()
     * @generated
     */
    EClass PANEL = eINSTANCE.getPanel();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PANEL__TITLE = eINSTANCE.getPanel_Title();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PANEL__COMPONENTS = eINSTANCE.getPanel_Components();

    /**
     * The meta object literal for the '{@link org.example.quickgui2.quickGUI.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.quickgui2.quickGUI.impl.ComponentImpl
     * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '{@link org.example.quickgui2.quickGUI.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.quickgui2.quickGUI.impl.FieldImpl
     * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__LABEL = eINSTANCE.getField_Label();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__NAME = eINSTANCE.getField_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIELD__TYPE = eINSTANCE.getField_Type();

    /**
     * The meta object literal for the '{@link org.example.quickgui2.quickGUI.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.quickgui2.quickGUI.impl.ButtonImpl
     * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__TEXT = eINSTANCE.getButton_Text();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUTTON__ACTION = eINSTANCE.getButton_Action();

    /**
     * The meta object literal for the '{@link org.example.quickgui2.quickGUI.FieldType <em>Field Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.quickgui2.quickGUI.FieldType
     * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getFieldType()
     * @generated
     */
    EEnum FIELD_TYPE = eINSTANCE.getFieldType();

    /**
     * The meta object literal for the '{@link org.example.quickgui2.quickGUI.ButtonAction <em>Button Action</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.example.quickgui2.quickGUI.ButtonAction
     * @see org.example.quickgui2.quickGUI.impl.QuickGUIPackageImpl#getButtonAction()
     * @generated
     */
    EEnum BUTTON_ACTION = eINSTANCE.getButtonAction();

  }

} //QuickGUIPackage
