/**
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.quickGUI;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Window</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.example.quickgui2.quickGUI.Window#getTitle <em>Title</em>}</li>
 *   <li>{@link org.example.quickgui2.quickGUI.Window#getPanel <em>Panel</em>}</li>
 * </ul>
 *
 * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getWindow()
 * @model
 * @generated
 */
public interface Window extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getWindow_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.example.quickgui2.quickGUI.Window#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Panel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Panel</em>' containment reference.
   * @see #setPanel(Panel)
   * @see org.example.quickgui2.quickGUI.QuickGUIPackage#getWindow_Panel()
   * @model containment="true"
   * @generated
   */
  Panel getPanel();

  /**
   * Sets the value of the '{@link org.example.quickgui2.quickGUI.Window#getPanel <em>Panel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Panel</em>' containment reference.
   * @see #getPanel()
   * @generated
   */
  void setPanel(Panel value);

} // Window
