/*
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class QuickGUIGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quickgui2.QuickGUI.Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoginAppKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cWindowAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cWindowWindowParserRuleCall_2_0 = (RuleCall)cWindowAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Program:
		//    'loginApp' '{'
		//        window=Window
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'loginApp' '{'
		//    window=Window
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'loginApp'
		public Keyword getLoginAppKeyword_0() { return cLoginAppKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//window=Window
		public Assignment getWindowAssignment_2() { return cWindowAssignment_2; }
		
		//Window
		public RuleCall getWindowWindowParserRuleCall_2_0() { return cWindowWindowParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class WindowElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quickgui2.QuickGUI.Window");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWindowKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleSTRINGTerminalRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPanelAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPanelPanelParserRuleCall_3_0 = (RuleCall)cPanelAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Window:
		//    'window' title=STRING '{'
		//        panel=Panel
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'window' title=STRING '{'
		//    panel=Panel
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'window'
		public Keyword getWindowKeyword_0() { return cWindowKeyword_0; }
		
		//title=STRING
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_1_0() { return cTitleSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//panel=Panel
		public Assignment getPanelAssignment_3() { return cPanelAssignment_3; }
		
		//Panel
		public RuleCall getPanelPanelParserRuleCall_3_0() { return cPanelPanelParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class PanelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quickgui2.QuickGUI.Panel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPanelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTitleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTitleSTRINGTerminalRuleCall_1_0 = (RuleCall)cTitleAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cComponentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cComponentsComponentParserRuleCall_3_0 = (RuleCall)cComponentsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Panel:
		//    'panel' title=STRING '{'
		//        components+=Component*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'panel' title=STRING '{'
		//    components+=Component*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'panel'
		public Keyword getPanelKeyword_0() { return cPanelKeyword_0; }
		
		//title=STRING
		public Assignment getTitleAssignment_1() { return cTitleAssignment_1; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_1_0() { return cTitleSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//components+=Component*
		public Assignment getComponentsAssignment_3() { return cComponentsAssignment_3; }
		
		//Component
		public RuleCall getComponentsComponentParserRuleCall_3_0() { return cComponentsComponentParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ComponentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quickgui2.QuickGUI.Component");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFieldParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cButtonParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Component:
		//      Field
		//    | Button
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  Field
		//| Button
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Field
		public RuleCall getFieldParserRuleCall_0() { return cFieldParserRuleCall_0; }
		
		//Button
		public RuleCall getButtonParserRuleCall_1() { return cButtonParserRuleCall_1; }
	}
	public class FieldElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quickgui2.QuickGUI.Field");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFieldKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLabelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLabelSTRINGTerminalRuleCall_1_0 = (RuleCall)cLabelAssignment_1.eContents().get(0);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameIDTerminalRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Keyword cTypeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTypeFieldTypeEnumRuleCall_5_0 = (RuleCall)cTypeAssignment_5.eContents().get(0);
		
		//Field:
		//    'field' label=STRING 'name' name=ID 'type' type=FieldType
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'field' label=STRING 'name' name=ID 'type' type=FieldType
		public Group getGroup() { return cGroup; }
		
		//'field'
		public Keyword getFieldKeyword_0() { return cFieldKeyword_0; }
		
		//label=STRING
		public Assignment getLabelAssignment_1() { return cLabelAssignment_1; }
		
		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_1_0() { return cLabelSTRINGTerminalRuleCall_1_0; }
		
		//'name'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//name=ID
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_3_0() { return cNameIDTerminalRuleCall_3_0; }
		
		//'type'
		public Keyword getTypeKeyword_4() { return cTypeKeyword_4; }
		
		//type=FieldType
		public Assignment getTypeAssignment_5() { return cTypeAssignment_5; }
		
		//FieldType
		public RuleCall getTypeFieldTypeEnumRuleCall_5_0() { return cTypeFieldTypeEnumRuleCall_5_0; }
	}
	public class ButtonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quickgui2.QuickGUI.Button");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cButtonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		private final Keyword cActionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActionButtonActionEnumRuleCall_3_0 = (RuleCall)cActionAssignment_3.eContents().get(0);
		
		//Button:
		//    'button' text=STRING 'action' action=ButtonAction
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'button' text=STRING 'action' action=ButtonAction
		public Group getGroup() { return cGroup; }
		
		//'button'
		public Keyword getButtonKeyword_0() { return cButtonKeyword_0; }
		
		//text=STRING
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_1_0() { return cTextSTRINGTerminalRuleCall_1_0; }
		
		//'action'
		public Keyword getActionKeyword_2() { return cActionKeyword_2; }
		
		//action=ButtonAction
		public Assignment getActionAssignment_3() { return cActionAssignment_3; }
		
		//ButtonAction
		public RuleCall getActionButtonActionEnumRuleCall_3_0() { return cActionButtonActionEnumRuleCall_3_0; }
	}
	
	public class FieldTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quickgui2.QuickGUI.FieldType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cTextEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cTextTextKeyword_0_0 = (Keyword)cTextEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cPasswordEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cPasswordPasswordKeyword_1_0 = (Keyword)cPasswordEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum FieldType:
		//      text='text'
		//    | password='password'
		//;
		public EnumRule getRule() { return rule; }
		
		//  text='text'
		//| password='password'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//text='text'
		public EnumLiteralDeclaration getTextEnumLiteralDeclaration_0() { return cTextEnumLiteralDeclaration_0; }
		
		//'text'
		public Keyword getTextTextKeyword_0_0() { return cTextTextKeyword_0_0; }
		
		//password='password'
		public EnumLiteralDeclaration getPasswordEnumLiteralDeclaration_1() { return cPasswordEnumLiteralDeclaration_1; }
		
		//'password'
		public Keyword getPasswordPasswordKeyword_1_0() { return cPasswordPasswordKeyword_1_0; }
	}
	public class ButtonActionElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.quickgui2.QuickGUI.ButtonAction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLoginEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLoginLoginKeyword_0_0 = (Keyword)cLoginEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCancelEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCancelCancelKeyword_1_0 = (Keyword)cCancelEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum ButtonAction:
		//      login='login'
		//    | cancel='cancel'
		//;
		public EnumRule getRule() { return rule; }
		
		//  login='login'
		//| cancel='cancel'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//login='login'
		public EnumLiteralDeclaration getLoginEnumLiteralDeclaration_0() { return cLoginEnumLiteralDeclaration_0; }
		
		//'login'
		public Keyword getLoginLoginKeyword_0_0() { return cLoginLoginKeyword_0_0; }
		
		//cancel='cancel'
		public EnumLiteralDeclaration getCancelEnumLiteralDeclaration_1() { return cCancelEnumLiteralDeclaration_1; }
		
		//'cancel'
		public Keyword getCancelCancelKeyword_1_0() { return cCancelCancelKeyword_1_0; }
	}
	
	private final ProgramElements pProgram;
	private final WindowElements pWindow;
	private final PanelElements pPanel;
	private final ComponentElements pComponent;
	private final FieldElements pField;
	private final ButtonElements pButton;
	private final FieldTypeElements eFieldType;
	private final ButtonActionElements eButtonAction;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public QuickGUIGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProgram = new ProgramElements();
		this.pWindow = new WindowElements();
		this.pPanel = new PanelElements();
		this.pComponent = new ComponentElements();
		this.pField = new FieldElements();
		this.pButton = new ButtonElements();
		this.eFieldType = new FieldTypeElements();
		this.eButtonAction = new ButtonActionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.example.quickgui2.QuickGUI".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Program:
	//    'loginApp' '{'
	//        window=Window
	//    '}'
	//;
	public ProgramElements getProgramAccess() {
		return pProgram;
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}
	
	//Window:
	//    'window' title=STRING '{'
	//        panel=Panel
	//    '}'
	//;
	public WindowElements getWindowAccess() {
		return pWindow;
	}
	
	public ParserRule getWindowRule() {
		return getWindowAccess().getRule();
	}
	
	//Panel:
	//    'panel' title=STRING '{'
	//        components+=Component*
	//    '}'
	//;
	public PanelElements getPanelAccess() {
		return pPanel;
	}
	
	public ParserRule getPanelRule() {
		return getPanelAccess().getRule();
	}
	
	//Component:
	//      Field
	//    | Button
	//;
	public ComponentElements getComponentAccess() {
		return pComponent;
	}
	
	public ParserRule getComponentRule() {
		return getComponentAccess().getRule();
	}
	
	//Field:
	//    'field' label=STRING 'name' name=ID 'type' type=FieldType
	//;
	public FieldElements getFieldAccess() {
		return pField;
	}
	
	public ParserRule getFieldRule() {
		return getFieldAccess().getRule();
	}
	
	//Button:
	//    'button' text=STRING 'action' action=ButtonAction
	//;
	public ButtonElements getButtonAccess() {
		return pButton;
	}
	
	public ParserRule getButtonRule() {
		return getButtonAccess().getRule();
	}
	
	//enum FieldType:
	//      text='text'
	//    | password='password'
	//;
	public FieldTypeElements getFieldTypeAccess() {
		return eFieldType;
	}
	
	public EnumRule getFieldTypeRule() {
		return getFieldTypeAccess().getRule();
	}
	
	//enum ButtonAction:
	//      login='login'
	//    | cancel='cancel'
	//;
	public ButtonActionElements getButtonActionAccess() {
		return eButtonAction;
	}
	
	public EnumRule getButtonActionRule() {
		return getButtonActionAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
