/*
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QuickGUIStandaloneSetup extends QuickGUIStandaloneSetupGenerated {

	public static void doSetup() {
		new QuickGUIStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
