/*
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QuickGUIRuntimeModule extends AbstractQuickGUIRuntimeModule {
}
