/*
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.example.quickgui2.parser.antlr.internal.InternalQuickGUIParser;
import org.example.quickgui2.services.QuickGUIGrammarAccess;

public class QuickGUIParser extends AbstractAntlrParser {

	@Inject
	private QuickGUIGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalQuickGUIParser createParser(XtextTokenStream stream) {
		return new InternalQuickGUIParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public QuickGUIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(QuickGUIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
