/*
 * generated by Xtext 2.42.0
 */
package org.example.quickgui2.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class QuickGUIAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/example/quickgui2/parser/antlr/internal/InternalQuickGUI.tokens");
	}
}
